<?php
namespace App\Services\Hosting;
use App\Models\HostingAccount; use App\Models\WebsiteActivity; use App\Models\WebsiteProvisioningRun; use Illuminate\Support\Str; use RuntimeException; use Throwable;
class WebsiteProvisioner {
 public function __construct(private HostingProviderManager $providers){}
 public function process(WebsiteProvisioningRun $run): WebsiteProvisioningRun { $run->load(['website','steps']); if(in_array($run->state,['complete'],true))return $run->fresh(['website','account','steps']); $run->update(['started_at'=>$run->started_at??now(),'attempts'=>$run->attempts+1]); try { foreach($run->steps as $step){if($step->status==='complete')continue;$this->step($run,$step);} $run->update(['state'=>'complete','completed_at'=>now(),'failed_step'=>null,'safe_error'=>null]);$run->website->update(['provisioning_status'=>'complete']);}catch(Throwable $e){$safeError=$e instanceof RuntimeException?$e->getMessage():'Provisioning failed. Review server logs.';if(isset($step))$step->update(['status'=>'failed','completed_at'=>now(),'safe_message'=>$safeError]);$run->update(['state'=>'failed','failed_step'=>$step->step??null,'safe_error'=>$safeError]);$run->website->update(['provisioning_status'=>'failed']); throw $e;} return $run->fresh(['website','account','steps']); }
 private function step($run,$step): void {$step->update(['status'=>'running','started_at'=>now(),'attempts'=>$step->attempts+1]);$run->update(['state'=>$this->state($step->step)]);$website=$run->website;$server=$run->hostingServer()->first(); if($step->step==='create_hosting'&&!$run->hosting_account_id){$this->guardLive();$provider=$this->providers->for($server);$username=$this->username($website->domain);$result=$provider->createAccount($server,['username'=>$username,'domain'=>$website->domain,'password'=>Str::password(24,true,true,false),'package_name'=>$run->hostingPackage()->value('name')]);$account=HostingAccount::updateOrCreate(['hosting_server_id'=>$server->id,'external_id'=>$result['external_id']],[...$result,'customer_id'=>$website->customer_id,'last_synced_at'=>now()]);$run->update(['hosting_account_id'=>$account->id]);$website->update(['hosting_account_id'=>$account->id,'cpanel_username'=>$account->username,'hosting_enabled'=>true]);} if(in_array($step->step,['install_wordpress','apply_profile','connect_agent'],true)&&$run->mode==='live') throw new RuntimeException('This WordPress step requires confirmed Krystal installation tooling and needs admin attention.'); $step->update(['status'=>'complete','completed_at'=>now(),'safe_message'=>ucwords(str_replace('_',' ',$step->step)).' complete.']);WebsiteActivity::create(['website_id'=>$website->id,'created_by_user_id'=>$run->initiated_by_user_id,'type'=>'provisioning_'.$step->step,'title'=>ucwords(str_replace('_',' ',$step->step)),'performed_at'=>now(),'visible_to_customer'=>in_array($step->step,['create_hosting','install_wordpress','complete'],true)]);}
 private function guardLive():void {if(config('hosting.provisioning_mode')==='live'&&!config('hosting.allow_live_provisioning'))throw new RuntimeException('Live hosting provisioning is disabled.');}
 private function username(string $domain):string{$base=preg_replace('/[^a-z0-9]/','',strtolower(strtok($domain,'.')));return substr($base?:'webstamp',0,12).substr(Str::lower(Str::random(3)),0,3);}
 private function state(string $s):string{return ['create_hosting'=>'creating_hosting','verify_hosting'=>'hosting_created','install_wordpress'=>'installing_wordpress','apply_profile'=>'configuring_wordpress','connect_agent'=>'connecting_agent','initial_check'=>'running_checks'][$s]??'pending';}
}
