<?php
/**
 * Plugin Name: WebStamp Site Agent
 * Description: Provides an authenticated, read-only health endpoint for the WebStamp CRM.
 * Version: 1.0.0
 */

if (!defined('ABSPATH')) exit;

add_action('rest_api_init', function (): void {
    register_rest_route('webstamp/v1', '/status', [
        'methods' => 'GET',
        'callback' => 'webstamp_agent_status',
        'permission_callback' => function (WP_REST_Request $request): bool {
            $configured = (string) get_option('webstamp_agent_token', '');
            $provided = (string) $request->get_header('x-webstamp-token');
            if (!$provided) {
                $authorization = (string) $request->get_header('authorization');
                if (stripos($authorization, 'Bearer ') === 0) $provided = substr($authorization, 7);
            }
            return $configured !== '' && $provided !== '' && hash_equals($configured, $provided);
        },
    ]);
});

function webstamp_agent_status(): WP_REST_Response {
    global $wpdb;
    $updates = wp_get_update_data();
    $theme = wp_get_theme();
    $databaseSize = (int) $wpdb->get_var("SELECT SUM(data_length + index_length) FROM information_schema.TABLES WHERE table_schema = DATABASE()");
    return new WP_REST_Response([
        'wordpress_version' => get_bloginfo('version'),
        'php_version' => PHP_VERSION,
        'plugin_updates' => (int) ($updates['counts']['plugins'] ?? 0),
        'theme_updates' => (int) ($updates['counts']['themes'] ?? 0),
        'database_size_bytes' => $databaseSize,
        'site_health_status' => 'good',
        'metrics' => ['active_theme' => $theme->get('Name'), 'debug_enabled' => defined('WP_DEBUG') && WP_DEBUG],
    ], 200);
}

add_action('admin_menu', function (): void {
    add_options_page('WebStamp Agent', 'WebStamp Agent', 'manage_options', 'webstamp-agent', 'webstamp_agent_settings_page');
});
add_action('admin_init', function (): void { register_setting('webstamp_agent', 'webstamp_agent_token', ['type' => 'string', 'sanitize_callback' => 'sanitize_text_field']); });
function webstamp_agent_settings_page(): void { ?>
    <div class="wrap"><h1>WebStamp Site Agent</h1><p>Paste the one-time token generated by your CRM website record. The endpoint is read-only and rejects unauthenticated requests.</p><form method="post" action="options.php"><?php settings_fields('webstamp_agent'); ?><table class="form-table"><tr><th><label for="webstamp_agent_token">Agent token</label></th><td><input class="regular-text" type="password" id="webstamp_agent_token" name="webstamp_agent_token" value="<?php echo esc_attr(get_option('webstamp_agent_token', '')); ?>"></td></tr></table><?php submit_button(); ?></form></div>
<?php }
