<?php
namespace Tests\Feature;
use App\Models\Customer; use App\Models\HostingAccount; use App\Models\HostingPackage; use App\Models\HostingServer; use App\Models\Role; use App\Models\User; use Database\Seeders\RolePermissionSeeder; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Http; use Tests\TestCase;
class HostingResellerProvisioningTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(RolePermissionSeeder::class);}
 public function test_credentials_are_encrypted_hidden_and_mock_connection_tests():void{$admin=$this->user('admin');$server=HostingServer::create(['name'=>'Krystal Trinity','provider'=>'krystal','api_type'=>'mock','credentials'=>['username'=>'reseller','token'=>'secret-token']]);$this->assertStringNotContainsString('secret-token',(string)$server->getRawOriginal('credentials'));$this->actingAs($admin)->getJson('/api/hosting-servers')->assertOk()->assertJsonMissing(['token'=>'secret-token'])->assertJsonPath('data.0.has_token',true);$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/test")->assertOk()->assertJsonPath('data.ok',true);}
 public function test_account_sync_is_idempotent_and_maps_to_customer_and_website():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Mock','api_type'=>'mock','metadata'=>['mock_accounts'=>[['external_id'=>'clienta','username'=>'clienta','primary_domain'=>'client.test','status'=>'active']]]]);$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/sync")->assertOk();$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/sync")->assertOk();$this->assertSame(1,HostingAccount::count());$website=\App\Models\Website::create(['customer_id'=>$customer->id,'name'=>'Client','domain'=>'client.test','login_url'=>'https://client.test']);$account=HostingAccount::first();$this->actingAs($admin)->putJson("/api/hosting-accounts/{$account->id}",['customer_id'=>$customer->id,'website_id'=>$website->id])->assertOk();$this->assertSame($account->id,$website->fresh()->hosting_account_id);}
 public function test_whm_adapter_tests_and_syncs_without_exposing_token():void{Http::fake(['https://whm.example.test:2087/json-api/listaccts*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['acct'=>[['user'=>'clienta','domain'=>'client-a.test','plan'=>'Standard','suspended'=>0]]]]),'https://whm.example.test:2087/json-api/listpkgs*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['pkg'=>[['name'=>'Standard','QUOTA'=>'5000']]]])]);$admin=$this->user('admin');$server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'whm-secret']]);$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/test")->assertOk();$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/sync")->assertOk()->assertJsonPath('data.accounts',1)->assertJsonPath('data.packages',1);$this->assertDatabaseHas('hosting_accounts',['username'=>'clienta']);$this->actingAs($admin)->getJson('/api/hosting-servers')->assertJsonMissing(['token'=>'whm-secret']);}
 public function test_mock_provisioning_is_idempotent_and_duplicate_domain_is_blocked():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$payload=$this->payload($customer,$server,$package);$first=$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertCreated()->assertJsonPath('data.state','complete');$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertCreated()->assertJsonPath('data.id',$first->json('data.id'));$this->assertDatabaseCount('websites',1);$this->assertDatabaseCount('hosting_accounts',1);$this->actingAs($admin)->postJson('/api/website-provisioning',[...$payload,'idempotency_key'=>'another-request'])->assertUnprocessable()->assertJsonValidationErrors('domain');}
 public function test_live_mode_fails_closed_and_customers_cannot_provision():void{config(['hosting.provisioning_mode'=>'live','hosting.allow_live_provisioning'=>false]);$admin=$this->user('admin');$customerUser=$this->user('customer');$customer=$this->customer($customerUser);[$server,$package]=$this->hosting();$payload=$this->payload($customer,$server,$package);$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertUnprocessable();$this->actingAs($customerUser)->postJson('/api/website-provisioning',$payload)->assertForbidden();$this->assertDatabaseCount('websites',0);}
 public function test_admin_without_provisioning_permission_cannot_provision():void{$admin=$this->user('admin');$admin->roles()->firstOrFail()->permissions()->where('slug','hosting_provision')->detach();$customer=$this->customer();[$server,$package]=$this->hosting();$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package))->assertForbidden();$this->assertDatabaseCount('websites',0);}
 public function test_failed_provisioning_preserves_local_record_and_never_deletes_hosting():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Unsupported','api_type'=>'cpanel']);$package=HostingPackage::create(['hosting_server_id'=>$server->id,'external_id'=>'standard','name'=>'Standard']);$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'failure.test'))->assertServerError();$this->assertDatabaseHas('websites',['domain'=>'failure.test','provisioning_status'=>'failed']);$this->assertDatabaseHas('website_provisioning_runs',['domain'=>'failure.test','state'=>'failed','failed_step'=>'create_hosting']);$this->assertDatabaseCount('hosting_accounts',0);}
 public function test_retry_resumes_at_the_failed_step_without_repeating_completed_steps():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Unsupported','api_type'=>'cpanel']);$package=HostingPackage::create(['hosting_server_id'=>$server->id,'external_id'=>'standard','name'=>'Standard']);$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'retry.test'))->assertServerError();$run=\App\Models\WebsiteProvisioningRun::firstOrFail();$this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'create_hosting','status'=>'failed','attempts'=>1]);$server->update(['api_type'=>'mock']);$this->actingAs($admin)->postJson("/api/website-provisioning/{$run->id}/retry")->assertAccepted();$this->assertDatabaseHas('website_provisioning_runs',['id'=>$run->id,'state'=>'complete']);$this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'create_hosting','status'=>'complete','attempts'=>2]);$this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'verify_hosting','status'=>'complete','attempts'=>1]);$this->assertDatabaseCount('hosting_accounts',1);}
 private function hosting():array{$s=HostingServer::create(['name'=>'Mock','api_type'=>'mock']);$p=HostingPackage::create(['hosting_server_id'=>$s->id,'external_id'=>'standard','name'=>'Standard']);return[$s,$p];} private function payload($c,$s,$p,string $domain='new-site.test'):array{return['customer_id'=>$c->id,'name'=>'New site','domain'=>$domain,'environment'=>'development','hosting_server_id'=>$s->id,'hosting_package_id'=>$p->id,'website_type'=>'wordpress','options'=>[],'idempotency_key'=>'same-request'];} private function user(string $role):User{$u=User::factory()->create();$u->roles()->attach(Role::where('slug',$role)->firstOrFail());return$u;} private function customer(?User $u=null):Customer{return Customer::create(['name'=>'Client','email'=>fake()->unique()->safeEmail(),'billing_address'=>'1 Test Road','user_id'=>$u?->id]);}
}
