<?php
namespace Tests\Feature;
use App\Models\Customer; use App\Models\HostingAccount; use App\Models\HostingPackage; use App\Models\HostingServer; use App\Models\Permission; use App\Models\Role; use App\Models\User; use Database\Seeders\RolePermissionSeeder; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Http; use Illuminate\Support\Facades\Schema; use Tests\TestCase;
class HostingResellerProvisioningTest extends TestCase {
 use RefreshDatabase;
 protected function setUp():void{parent::setUp();$this->seed(RolePermissionSeeder::class);}
 public function test_credentials_are_encrypted_hidden_and_mock_connection_tests():void{$admin=$this->user('admin');$server=HostingServer::create(['name'=>'Krystal Trinity','provider'=>'krystal','api_type'=>'mock','credentials'=>['username'=>'reseller','token'=>'secret-token']]);$this->assertStringNotContainsString('secret-token',(string)$server->getRawOriginal('credentials'));$this->actingAs($admin)->getJson('/api/hosting-servers')->assertOk()->assertJsonMissing(['token'=>'secret-token'])->assertJsonPath('data.0.has_token',true);$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/test")->assertOk()->assertJsonPath('data.ok',true);}
 public function test_permission_migration_repairs_existing_admin_role_assignments():void{$adminRole=Role::where('slug','admin')->firstOrFail();$slugs=['hosting_view','hosting_manage','hosting_provision','hosting_credentials','hosting_terminate'];$permissionIds=Permission::whereIn('slug',$slugs)->pluck('id');$adminRole->permissions()->detach($permissionIds);Permission::whereIn('slug',$slugs)->delete();$migration=require database_path('migrations/2026_08_16_000000_ensure_hosting_permissions_for_admin_role.php');$migration->up();$this->assertSame(5,Permission::whereIn('slug',$slugs)->count());$this->assertSame(5,$adminRole->permissions()->whereIn('slug',$slugs)->count());$admin=$this->user('admin');$this->actingAs($admin)->getJson('/api/website-provisioning/options')->assertOk();}
 public function test_reseller_migration_resumes_after_a_partial_mysql_application():void{Schema::disableForeignKeyConstraints();Schema::dropIfExists('website_provisioning_steps');Schema::dropIfExists('website_provisioning_runs');Schema::dropIfExists('wordpress_profiles');Schema::dropIfExists('hosting_packages');Schema::enableForeignKeyConstraints();$this->assertTrue(Schema::hasTable('hosting_accounts'));$migration=require database_path('migrations/2026_08_15_010000_create_reseller_hosting_and_provisioning_tables.php');$migration->up();foreach(['hosting_accounts','hosting_packages','wordpress_profiles','website_provisioning_runs','website_provisioning_steps']as$table)$this->assertTrue(Schema::hasTable($table));$this->assertTrue(Schema::hasColumn('websites','hosting_account_id'));$this->assertTrue(Schema::hasColumn('websites','provisioning_status'));}
 public function test_admin_can_access_all_hosting_setup_reads_and_actions_without_exposing_token():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Krystal Trinity','provider'=>'krystal','api_type'=>'mock','credentials'=>['username'=>'reseller','token'=>'never-return-this-token'],'metadata'=>['mock_accounts'=>[['external_id'=>'clienta','username'=>'clienta','primary_domain'=>'client.test','status'=>'active']]]]);$options=$this->actingAs($admin)->getJson('/api/website-provisioning/options')->assertOk()->assertJsonPath('data.servers.0.id',$server->id)->assertJsonPath('data.servers.0.credential_username','reseller')->assertJsonPath('data.servers.0.has_token',true);$this->assertStringNotContainsString('never-return-this-token',$options->getContent());$accounts=$this->actingAs($admin)->getJson('/api/website-provisioning/hosting-accounts')->assertOk();$this->assertStringNotContainsString('never-return-this-token',$accounts->getContent());$servers=$this->actingAs($admin)->getJson('/api/hosting-servers')->assertOk()->assertJsonPath('data.0.credential_username','reseller')->assertJsonPath('data.0.has_token',true);$this->assertStringNotContainsString('never-return-this-token',$servers->getContent());$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/test")->assertOk();$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/sync")->assertOk()->assertJsonPath('data.accounts',1);$this->actingAs($admin)->getJson('/api/website-provisioning/hosting-accounts')->assertOk()->assertJsonPath('data.0.username','clienta');}
 public function test_non_admins_remain_forbidden_from_all_hosting_setup_endpoints():void{$customerUser=$this->user('customer');$staff=$this->user('staff');$server=HostingServer::create(['name'=>'Mock','api_type'=>'mock']);foreach([$customerUser,$staff]as$user){$this->actingAs($user)->getJson('/api/website-provisioning/options')->assertForbidden();$this->actingAs($user)->getJson('/api/website-provisioning/hosting-accounts')->assertForbidden();$this->actingAs($user)->getJson('/api/hosting-servers')->assertForbidden();$this->actingAs($user)->postJson("/api/hosting-servers/{$server->id}/test")->assertForbidden();$this->actingAs($user)->postJson("/api/hosting-servers/{$server->id}/sync")->assertForbidden();}}
 public function test_admin_can_save_ssh_fingerprint_without_erasing_other_server_metadata():void{$admin=$this->user('admin');$server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'secret'],'metadata'=>['existing_setting'=>'kept']]);$fingerprint='SHA256:'.str_repeat('a',43);$this->actingAs($admin)->putJson("/api/hosting-servers/{$server->id}",['metadata'=>['ssh_host_fingerprint'=>$fingerprint]])->assertOk();$server->refresh();$this->assertSame('kept',$server->metadata['existing_setting']);$this->assertSame($fingerprint,$server->metadata['ssh_host_fingerprint']);$this->actingAs($admin)->getJson('/api/website-provisioning/options')->assertOk()->assertJsonPath('data.servers.0.ssh_host_fingerprint',$fingerprint);}
 public function test_account_sync_is_idempotent_and_maps_to_customer_and_website():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Mock','api_type'=>'mock','metadata'=>['mock_accounts'=>[['external_id'=>'clienta','username'=>'clienta','primary_domain'=>'client.test','status'=>'active']]]]);$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/sync")->assertOk();$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/sync")->assertOk();$this->assertSame(1,HostingAccount::count());$website=\App\Models\Website::create(['customer_id'=>$customer->id,'name'=>'Client','domain'=>'client.test','login_url'=>'https://client.test']);$account=HostingAccount::first();$this->actingAs($admin)->putJson("/api/hosting-accounts/{$account->id}",['customer_id'=>$customer->id,'website_id'=>$website->id])->assertOk();$this->assertSame($account->id,$website->fresh()->hosting_account_id);}
 public function test_whm_adapter_tests_and_syncs_without_exposing_token():void{Http::fake(['https://whm.example.test:2087/json-api/listaccts*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['acct'=>[['user'=>'clienta','domain'=>'client-a.test','plan'=>'Standard','suspended'=>0]]]]),'https://whm.example.test:2087/json-api/listpkgs*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['pkg'=>[['name'=>'Standard','QUOTA'=>'5000']]]])]);$admin=$this->user('admin');$server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'whm-secret']]);$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/test")->assertOk();$this->actingAs($admin)->postJson("/api/hosting-servers/{$server->id}/sync")->assertOk()->assertJsonPath('data.accounts',1)->assertJsonPath('data.packages',1);$this->assertDatabaseHas('hosting_accounts',['username'=>'clienta']);$this->actingAs($admin)->getJson('/api/hosting-servers')->assertJsonMissing(['token'=>'whm-secret']);}
 public function test_mock_provisioning_is_idempotent_and_duplicate_domain_is_blocked():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$payload=$this->payload($customer,$server,$package);$first=$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertCreated()->assertJsonPath('data.state','complete');$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertCreated()->assertJsonPath('data.id',$first->json('data.id'));$this->assertDatabaseCount('websites',1);$this->assertDatabaseCount('hosting_accounts',1);$this->actingAs($admin)->postJson('/api/website-provisioning',[...$payload,'idempotency_key'=>'another-request'])->assertUnprocessable()->assertJsonValidationErrors('domain');}
 public function test_deleted_domain_can_be_provisioned_again_without_losing_history():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$payload=$this->payload($customer,$server,$package,'copperingots.uk');$first=$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertCreated();$websiteId=$first->json('data.website.id');$this->actingAs($admin)->postJson("/api/websites/{$websiteId}/delete",['deletion_type'=>'crm_only','confirmation'=>'copperingots.uk','idempotency_key'=>(string)\Illuminate\Support\Str::uuid()])->assertOk();$second=$this->actingAs($admin)->postJson('/api/website-provisioning',[...$payload,'idempotency_key'=>'copperingots-second-attempt'])->assertCreated();$this->assertNotSame($first->json('data.id'),$second->json('data.id'));$this->assertDatabaseCount('website_provisioning_runs',2);$this->assertSame(2,\App\Models\Website::withTrashed()->where('domain','copperingots.uk')->count());}
 public function test_mock_preview_never_reports_verified_hosting_or_monitoring():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$response=$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'preview.test'))->assertCreated();$websiteId=$response->json('data.website.id');$this->assertDatabaseHas('websites',['id'=>$websiteId,'provisioning_status'=>'preview_complete','agent_last_seen_at'=>null]);$this->assertNull(HostingAccount::firstOrFail()->last_synced_at);$this->actingAs($admin)->getJson("/api/websites/{$websiteId}")->assertOk()->assertJsonPath('data.hosting_connected',false)->assertJsonPath('data.agent_connected',false);}
 public function test_production_rejects_mock_provisioning_instead_of_claiming_success():void{$original=$this->app['env'];$this->app['env']='production';config(['hosting.provisioning_mode'=>'mock']);try{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'never-fake.test'))->assertUnprocessable()->assertJsonValidationErrors('provisioning');$this->assertDatabaseCount('websites',0);}finally{$this->app['env']=$original;}}
 public function test_whm_verification_requires_the_exact_subdomain_and_assigned_ip():void{Http::fake(['https://whm.example.test:2087/json-api/listaccts*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['acct'=>[['user'=>'dev4site','domain'=>'other.web-stamp.co.uk','ip'=>'1.2.3.4','suspended'=>0]]]])]);$server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'secret']]);$account=HostingAccount::create(['hosting_server_id'=>$server->id,'external_id'=>'dev4site','username'=>'dev4site','primary_domain'=>'dev4.web-stamp.co.uk','status'=>'pending']);$this->expectException(\RuntimeException::class);$this->expectExceptionMessage('unexpected primary domain');app(\App\Services\Hosting\KrystalWhmProvider::class)->verifyAccount($server,$account);}

 public function test_whm_package_shell_access_is_refreshed_and_requested_during_account_creation():void
 {
  Http::fake([
   'https://whm.example.test:2087/json-api/listaccts*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['acct'=>[]]]),
   'https://whm.example.test:2087/json-api/listpkgs*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['pkg'=>[['name'=>'Standard','HASSHELL'=>'1']]]]),
   'https://whm.example.test:2087/json-api/createacct*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'Account created'],'data'=>['ip'=>'1.2.3.4']]),
  ]);
  $server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'secret'],'metadata'=>['ssh_host_fingerprint'=>str_repeat('a',64)]]);
  $provider=app(\App\Services\Hosting\KrystalWhmProvider::class);
  $this->assertTrue($provider->packages($server)[0]['shell_access']);
  $provider->createAccount($server,['username'=>'newsite','domain'=>'newsite.test','password'=>'not-logged','package_name'=>'Standard','shell_access'=>true]);
  Http::assertSent(fn($request)=>str_contains($request->url(),'/createacct')&&$request['hasshell']===1);
 }
 public function test_whm_account_creation_reconciles_an_account_created_after_an_earlier_timeout():void
 {
  Http::fake(['https://whm.example.test:2087/json-api/listaccts*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['acct'=>[['user'=>'recovered1','domain'=>'recovered.test','ip'=>'1.2.3.4','plan'=>'Standard','suspended'=>0]]]])]);
  $server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'secret'],'metadata'=>['ssh_host_fingerprint'=>str_repeat('a',64)]]);
  $result=app(\App\Services\Hosting\KrystalWhmProvider::class)->createAccount($server,['username'=>'different1','domain'=>'recovered.test','password'=>'not-logged','package_name'=>'Standard','shell_access'=>true]);
  $this->assertSame('recovered1',$result['username']);
  $this->assertTrue($result['metadata']['reconciled_existing_account']);
  Http::assertNotSent(fn($request)=>str_contains($request->url(),'/createacct'));
 }
 public function test_live_retry_refreshes_stale_shell_access_before_creating_the_account():void
 {
  config(['hosting.provisioning_mode'=>'live','hosting.allow_live_provisioning'=>true]);
  Http::fake([
   'https://whm.example.test:2087/json-api/listpkgs*'=>Http::sequence()
    ->push(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['pkg'=>[['name'=>'Standard','HASSHELL'=>0]]]])
    ->push(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['pkg'=>[['name'=>'Standard','HASSHELL'=>1]]]]),
   'https://whm.example.test:2087/json-api/listaccts*'=>Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['acct'=>[]]]),
   'https://whm.example.test:2087/json-api/createacct*'=>Http::response(['metadata'=>['result'=>0,'reason'=>'Stopped after prerequisite test']]),
  ]);
  $admin=$this->user('admin');$customer=$this->customer();
  $server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'secret'],'metadata'=>['ssh_host_fingerprint'=>str_repeat('a',64)]]);
  $package=HostingPackage::create(['hosting_server_id'=>$server->id,'external_id'=>'Standard','name'=>'Standard','shell_access'=>false]);
  $this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'refresh-shell.test'))->assertCreated();
  $run=\App\Models\WebsiteProvisioningRun::firstOrFail();
  $this->assertSame('validate_prerequisites',$run->fresh()->failed_step);
  $this->assertFalse($package->fresh()->shell_access);
  $this->actingAs($admin)->postJson("/api/website-provisioning/{$run->id}/retry")->assertAccepted();
  $this->assertTrue($package->fresh()->shell_access);
  $this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'validate_prerequisites','status'=>'complete','attempts'=>2]);
  $this->assertDatabaseHas('website_provisioning_runs',['id'=>$run->id,'failed_step'=>'create_cpanel_account']);
  Http::assertSent(fn($request)=>str_contains($request->url(),'/createacct')&&$request['hasshell']===1);
 }
 public function test_complete_live_wordpress_pipeline_reaches_every_stage_without_false_success():void
 {
  config(['hosting.provisioning_mode'=>'live','hosting.allow_live_provisioning'=>true]);
  $createdUsername=null;
  Http::fake(function($request)use(&$createdUsername){$url=$request->url();if(str_contains($url,'/listpkgs'))return Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['pkg'=>[['name'=>'Standard','HASSHELL'=>1]]]]);if(str_contains($url,'/listaccts'))return Http::response(['metadata'=>['result'=>1,'reason'=>'OK'],'data'=>['acct'=>$createdUsername?[['user'=>$createdUsername,'domain'=>'pipeline.test','ip'=>'1.2.3.4','plan'=>'Standard','suspended'=>0]]:[]]]);if(str_contains($url,'/createacct')){$createdUsername=$request['username'];return Http::response(['metadata'=>['result'=>1,'reason'=>'Account created'],'data'=>['ip'=>'1.2.3.4']]);}if(str_starts_with($url,'http://pipeline.test/'))return Http::response('',301,['Location'=>'https://pipeline.test/']);if(str_starts_with($url,'https://pipeline.test/'))return Http::response('',200);return Http::response([],404);});
  $ssh=new class implements \App\Contracts\SshCommandRunner { public array $commands=[]; public function run(HostingServer $server,HostingAccount $account,string $password,string $command,int $timeout=60):array{$this->commands[]=$command;if(str_contains($command,"'option' 'get' 'siteurl'"))return['exit_code'=>0,'output'=>'https://pipeline.test'];if(str_contains($command,"'db' 'tables'"))return['exit_code'=>0,'output'=>'wp_posts'];if(str_contains($command,"'Mysql' 'get_restrictions'"))return['exit_code'=>0,'output'=>'{"result":{"status":1,"data":{"prefix":"pipeline_","max_database_name_length":64,"max_username_length":32}}}'];if(str_contains($command,'uapi --output=json'))return['exit_code'=>0,'output'=>'{"result":{"status":1}}'];if(str_contains($command,'test -f public_html/wp-load.php')||str_contains($command,"'core' 'is-installed'"))return['exit_code'=>1,'output'=>''];return['exit_code'=>0,'output'=>''];} };
  $this->app->instance(\App\Contracts\SshCommandRunner::class,$ssh);
  $this->app->instance(\App\Contracts\DnsResolver::class,new class implements \App\Contracts\DnsResolver { public function aRecords(string $host):array{return['1.2.3.4'];}public function cnameRecords(string $host):array{return[];}public function nameservers(string $host):array{return[];} });
  $this->app->instance(\App\Contracts\SslInspector::class,new class implements \App\Contracts\SslInspector { public function inspect(string $host):array{return['valid'=>true,'hostname_match'=>true,'issuer'=>'Test CA','expires_at'=>now()->addDays(30)->toIso8601String(),'error'=>null];} });
  $admin=$this->user('admin');$customer=$this->customer();
  $server=HostingServer::create(['name'=>'Krystal','api_type'=>'whm','hostname'=>'whm.example.test','credentials'=>['username'=>'reseller','token'=>'secret'],'metadata'=>['ssh_host_fingerprint'=>str_repeat('a',64)]]);
  $package=HostingPackage::create(['hosting_server_id'=>$server->id,'external_id'=>'Standard','name'=>'Standard','shell_access'=>true]);
  $response=$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'pipeline.test'))->assertCreated();
  $run=\App\Models\WebsiteProvisioningRun::firstOrFail();
  $this->assertSame('complete',$run->fresh()->state,json_encode(['failed_step'=>$run->fresh()->failed_step,'safe_error'=>$run->fresh()->safe_error]));
  $this->assertDatabaseMissing('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'status'=>'failed']);
  $this->assertSame(1,$run->steps()->where('status','manual_action')->where('step','install_agent')->count());
  $this->assertSame($run->steps()->count()-1,$run->steps()->where('status','complete')->count());
  $this->assertNotNull($createdUsername);
  $this->assertDatabaseHas('hosting_accounts',['username'=>$createdUsername,'primary_domain'=>'pipeline.test','assigned_ip'=>'1.2.3.4']);
  $this->assertDatabaseHas('websites',['domain'=>'pipeline.test','provisioning_status'=>'complete','status'=>'healthy']);
  $this->assertStringNotContainsString('secret',strtolower($response->getContent()));
  $this->assertNotEmpty($ssh->commands);
 }
 public function test_repair_migration_removes_only_unverified_mock_connections():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$response=$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'fake-preview.test'))->assertCreated();$website=\App\Models\Website::findOrFail($response->json('data.website.id'));$website->update(['agent_last_seen_at'=>now(),'monitoring_enabled'=>true]);$accountId=$website->hosting_account_id;$migration=require database_path('migrations/2026_08_22_000200_repair_mock_provisioning_false_positives.php');$migration->up();$website->refresh();$this->assertNull($website->hosting_account_id);$this->assertNull($website->agent_last_seen_at);$this->assertSame('failed',$website->provisioning_status);$this->assertDatabaseMissing('hosting_accounts',['id'=>$accountId]);}
 public function test_repair_migration_preserves_a_later_real_whm_mapping():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$response=$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'real-after-preview.test'))->assertCreated();$website=\App\Models\Website::findOrFail($response->json('data.website.id'));$account=$website->hostingAccount;$account->update(['metadata'=>['owner'=>'reseller'],'last_synced_at'=>now()]);$before=$website->provisioning_status;$migration=require database_path('migrations/2026_08_22_000200_repair_mock_provisioning_false_positives.php');$migration->up();$this->assertSame($account->id,$website->fresh()->hosting_account_id);$this->assertSame($before,$website->fresh()->provisioning_status);}
 public function test_generated_wordpress_credentials_are_encrypted_hidden_and_revealed_once():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$response=$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'credentials.test'))->assertCreated();$websiteId=$response->json('data.website.id');$this->assertStringNotContainsString('password',strtolower($response->getContent()));$credential=\App\Models\WebsiteCredential::firstOrFail();$this->assertNotSame($credential->secret_encrypted,$credential->getRawOriginal('secret_encrypted'));$this->actingAs($admin)->postJson("/api/websites/{$websiteId}/reveal-credential")->assertOk()->assertJsonPath('data.username','webstamp_admin');$this->actingAs($admin)->postJson("/api/websites/{$websiteId}/reveal-credential")->assertStatus(410);}
 public function test_live_mode_fails_closed_and_customers_cannot_provision():void{config(['hosting.provisioning_mode'=>'live','hosting.allow_live_provisioning'=>false]);$admin=$this->user('admin');$customerUser=$this->user('customer');$customer=$this->customer($customerUser);[$server,$package]=$this->hosting();$payload=$this->payload($customer,$server,$package);$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertUnprocessable();$this->actingAs($customerUser)->postJson('/api/website-provisioning',$payload)->assertForbidden();$this->assertDatabaseCount('websites',0);}
 public function test_admin_without_provisioning_permission_cannot_provision():void{$admin=$this->user('admin');$admin->roles()->firstOrFail()->permissions()->where('slug','hosting_provision')->detach();$customer=$this->customer();[$server,$package]=$this->hosting();$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package))->assertForbidden();$this->assertDatabaseCount('websites',0);}
 public function test_failed_provisioning_preserves_local_record_and_never_deletes_hosting():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Mock failure','api_type'=>'mock','metadata'=>['mock_fail_steps'=>['create_cpanel_account']]]);$package=HostingPackage::create(['hosting_server_id'=>$server->id,'external_id'=>'standard','name'=>'Standard']);$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'failure.test'))->assertCreated()->assertJsonPath('data.state','failed');$this->assertDatabaseHas('websites',['domain'=>'failure.test','provisioning_status'=>'failed']);$this->assertNotNull(\App\Models\Website::where('domain','failure.test')->value('cpanel_username'));$this->assertDatabaseHas('website_provisioning_runs',['domain'=>'failure.test','state'=>'failed','failed_step'=>'create_cpanel_account']);$this->assertDatabaseCount('hosting_accounts',0);}
 public function test_retry_resumes_at_the_failed_step_without_repeating_completed_steps():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Mock failure','api_type'=>'mock','metadata'=>['mock_fail_steps'=>['wait_for_cpanel']]]);$package=HostingPackage::create(['hosting_server_id'=>$server->id,'external_id'=>'standard','name'=>'Standard']);$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'retry.test'))->assertCreated()->assertJsonPath('data.state','failed');$run=\App\Models\WebsiteProvisioningRun::firstOrFail();$this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'create_cpanel_account','status'=>'complete','attempts'=>1]);$this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'wait_for_cpanel','status'=>'failed','attempts'=>1]);$server->update(['metadata'=>[]]);$this->actingAs($admin)->postJson("/api/website-provisioning/{$run->id}/retry")->assertAccepted();$this->assertDatabaseHas('website_provisioning_runs',['id'=>$run->id,'state'=>'complete']);$this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'create_cpanel_account','status'=>'complete','attempts'=>1]);$this->assertDatabaseHas('website_provisioning_steps',['website_provisioning_run_id'=>$run->id,'step'=>'wait_for_cpanel','status'=>'complete','attempts'=>2]);$this->assertDatabaseCount('hosting_accounts',1);}
 public function test_unsafe_domain_and_wordpress_admin_inputs_are_rejected_before_any_account_is_created():void{$admin=$this->user('admin');$customer=$this->customer();[$server,$package]=$this->hosting();$payload=$this->payload($customer,$server,$package,'safe.test');$payload['domain']='safe.test; touch bad';$payload['options']=['admin_username'=>'admin'];$this->actingAs($admin)->postJson('/api/website-provisioning',$payload)->assertUnprocessable()->assertJsonValidationErrors(['domain','options.admin_username']);$this->assertDatabaseCount('websites',0);$this->assertDatabaseCount('hosting_accounts',0);}
 public function test_temporary_cpanel_and_database_secrets_are_encrypted_and_never_returned():void{$admin=$this->user('admin');$customer=$this->customer();$server=HostingServer::create(['name'=>'Mock pause','api_type'=>'mock','metadata'=>['mock_fail_steps'=>['wait_for_cpanel']]]);$package=HostingPackage::create(['hosting_server_id'=>$server->id,'external_id'=>'standard','name'=>'Standard']);$response=$this->actingAs($admin)->postJson('/api/website-provisioning',$this->payload($customer,$server,$package,'encrypted.test'))->assertCreated();$run=\App\Models\WebsiteProvisioningRun::firstOrFail();$this->assertArrayHasKey('cpanel_password',$run->secrets_encrypted);$this->assertArrayHasKey('database_password',$run->secrets_encrypted);$raw=(string)$run->getRawOriginal('secrets_encrypted');$this->assertStringNotContainsString($run->secrets_encrypted['cpanel_password'],$raw);$this->assertStringNotContainsString($run->secrets_encrypted['cpanel_password'],$response->getContent());$this->assertStringNotContainsString($run->secrets_encrypted['database_password'],$response->getContent());}
 private function hosting():array{$s=HostingServer::create(['name'=>'Mock','api_type'=>'mock']);$p=HostingPackage::create(['hosting_server_id'=>$s->id,'external_id'=>'standard','name'=>'Standard']);return[$s,$p];} private function payload($c,$s,$p,string $domain='new-site.test'):array{return['customer_id'=>$c->id,'name'=>'New site','domain'=>$domain,'environment'=>'development','hosting_server_id'=>$s->id,'hosting_package_id'=>$p->id,'website_type'=>'wordpress','options'=>[],'idempotency_key'=>'same-request'];} private function user(string $role):User{$u=User::factory()->create();$u->roles()->attach(Role::where('slug',$role)->firstOrFail());return$u;} private function customer(?User $u=null):Customer{return Customer::create(['name'=>'Client','email'=>fake()->unique()->safeEmail(),'billing_address'=>'1 Test Road','user_id'=>$u?->id]);}
}
